let arrayJuegos = [
  {nombre: "Salón de Fiestas", precio: 25000, foto: "foto3.jpg", descripcion: "Salon de fiestas Taurum, incluye freezer grande, horno pizzero, microondas, aire acondicionado frio calor, y ventilador. Se entrega limpio a las 10 de la mañana hasta las 18hs o desde las 20hs hasta las 4 de la madrugada, los 2 turnos juntos $7000 mas. Al finalizar nos encargamos nosotros de la limpieza. La capacidad es hasta 120 personas."},
  {nombre: "Dj, Sonido e Iluminación", precio: 22000, foto: "sonido.jpg", descripcion: "Dj en vivo mas sonido e iluminación en el salón, el servicio es de 7 horas. En nuestro salón"},
  {nombre: "Proyector y Pantalla", precio: 9000, foto: "pantalla.jpg", descripcion: "Proyector mas pantalla grande para la proyección de video. En nuestro salón"},
  {nombre: "Animador", precio: 13000, foto: "animador.jpg", descripcion: "El animador es como el locutor de la fiesta, el que le pone onda, no es animación para niños. El servicio es de 6 horas En nuestro salón"},
  {nombre: "Parlante chico mas luces", precio: 9000, foto: "parlante.jpg", descripcion: "Parlante chico con conección bluetooth, cable o pendrive. Cuenta con luz láser y 2 luces audiorítmicas. En nuestro salón"},
  {nombre: "Ornamentación", precio: 20000, foto: "foto7.jpg", descripcion: "La ornamentación es para nuestro salón, incluye colgado y armado de telas, cortinado, accesorios y algunos globos, puede agregar mas si desea."},
  {nombre: "Servicio de vestir", precio: 2000, foto: "foto8.jpg", descripcion: "El servicio de vestir mesas y sillas incluye solo el trabajo de armar 1 mesa con su mantel y cubremesas mas las 10 sillas con sus vestidos y moños, tambien servilleteros y centros de mesa, copas, etc si las encarga. En nuestro salón"},
  {nombre: "Panchera Grande", precio: 5000, foto: "panchera.jpg", descripcion: "Panchera grande, no incluye el gas, puede pedir con gas sumandole el precio de la carga de gas de la garrafa. Costo de envío dependiendo la zona."},
  {nombre: "Candelabro 15 velas", precio: 4500, foto: "candelabro.jpg", descripcion: "Candelabro para poner las 15 velas de los 15 años. Costo de envío dependiendo la zona."},
  {nombre: "Freezer Grande", precio: 5500, foto: "freezer.jpg", descripcion: "Freezer grande 460 litros 1,65mts x 0,70mt. Costo de envío dependiendo la zona."},
  {nombre: "Barra de Tragos", precio: 5000, foto: "barra.jpg", descripcion: "Barra de tragos con luces mas enchufes para licuadora y demas accesorios que necesite enchufar. Costo de envío dependiendo la zona."},
  {nombre: "Sillas Princesas", precio: 120, foto: "silla.jpg", descripcion: "Silla plastica negra estilo princesa. Costo de envío dependiendo la zona."},
  {nombre: "Vestido de Sillas", precio: 120, foto: "vestido.jpg", descripcion: "Vestido para silla princesa color blanco. Costo de envío dependiendo la zona."},
  {nombre: "Lazo de Silla", precio: 30, foto: "moños.jpg", descripcion: "Lazos para los moños de las sillas, colores a elección. Costo de envío dependiendo la zona."},
  {nombre: "Mesa Ovalada", precio: 1000, foto: "ovalada.jpg", descripcion: "Mesa ovalada, para 10 personas. Costo de envío dependiendo la zona."},
  {nombre: "Mesa Rectangular", precio: 1000, foto: "rectangular.jpg", descripcion: "Mesa rectangular, para 10 personas, medida aproximada 1.80 metros. Costo de envío dependiendo la zona."},
  {nombre: "Mantel Ovalado", precio: 1000, foto: "mantelred.jpg", descripcion: "Mantel ovalado color blanco. Costo de envío dependiendo la zona."},
  {nombre: "Mantel Rectangular", precio: 1000, foto: "mantrect.jpg", descripcion: "Mantel rectangular color blanco. Costo de envío dependiendo la zona."},
  {nombre: "Camino de Mesa", precio: 350, foto: "camino.jpg", descripcion: "Caminos de mesa de colores varios. Costo de envío dependiendo la zona."},
  {nombre: "Alfombra Roja", precio: 4500, foto: "alfombra.jpg", descripcion: "Alfombra roja de unos 10 metros de largo por 1.50 para entradas. Costo de envío dependiendo la zona."},
  {nombre: "Candy Bar Carrosa", precio: 5500, foto: "candy.jpg", descripcion: "Candy bar grande en forma de carrosa, mesa con marco de selfile atras y ruedas de carruaje mas caballo. Para poner la torta y/o mesa dulce. Costo de envío dependiendo la zona."},
  {nombre: "Cuchillo", precio: 15, foto: "cuchillo.jpg", descripcion: "Cuchillo. Costo de envío dependiendo la zona."},
  {nombre: "Tenedor", precio: 15, foto: "tenedor.jpg", descripcion: "Tenedor. Costo de envío dependiendo la zona."},
  {nombre: "Cuchara", precio: 15, foto: "cuchara.jpg", descripcion: "Cuchara. Costo de envío dependiendo la zona."},
  {nombre: "Cucharita", precio: 15, foto: "cucharita.jpg", descripcion: "Cucharita postre. Costo de envío dependiendo la zona."},
  {nombre: "Panera", precio: 80, foto: "panera.jpg", descripcion: "Panera plástica. Costo de envío dependiendo la zona."},
  {nombre: "Jarra de Vidrio", precio: 160, foto: "jarra.jpg", descripcion: "Jarra de vidrio de 1 litro aproximadamente. Costo de envío dependiendo la zona."},
  {nombre: "Bandeja de Moso", precio: 250, foto: "bandeja.jpg", descripcion: "Bandeja de moso plateada grande. Costo de envío dependiendo la zona."},
  {nombre: "Salero", precio: 70, foto: "salero.jpg", descripcion: "Salero. Costo de envío dependiendo la zona."},
  {nombre: "Servilletero", precio: 70, foto: "servilletero.jpg", descripcion: "Servilletero de metal. Costo de envío dependiendo la zona."},
  {nombre: "Ensaladera", precio: 120, foto: "ensaladera.jpg", descripcion: "Ensaladera de vidrio. Costo de envío dependiendo la zona."},
  {nombre: "Compotera", precio: 80, foto: "compotera.jpg", descripcion: "Compotera de vidrio. Costo de envío dependiendo la zona."},
  {nombre: "Hielera", precio: 100, foto: "hielera.jpg", descripcion: "Hilera de metal con pinza. Costo de envío dependiendo la zona."},
  {nombre: "Platito de Postre", precio: 70, foto: "platito.jpg", descripcion: "Plato chico de postre, de porcelana. Costo de envío dependiendo la zona."},
  {nombre: "Plato playo", precio: 80, foto: "plato.jpg", descripcion: "Plato playo principal de porcelana. Costo de envío dependiendo la zona."},
  {nombre: "Copa", precio: 60, foto: "copa.jpg", descripcion: "Copa de vidrio estilo copa de vino. Costo de envío dependiendo la zona."},
  {nombre: "Copa Champagne", precio: 60, foto: "champagne.jpg", descripcion: "Copa fina para champagne. Costo de envío dependiendo la zona."},
  {nombre: "Vaso Trago Largo", precio: 60, foto: "vaso.jpg", descripcion: "Vaso fino alto estilo trago largo. Costo de envío dependiendo la zona."},
  {nombre: "Taza con Platito", precio: 90, foto: "taza.jpg", descripcion: "Taza con platito de porcelana. Costo de envío dependiendo la zona."},
  {nombre: "Azucarera", precio: 90, foto: "azucarera.jpg", descripcion: "Azucarera de vidrio y metal. Costo de envío dependiendo la zona."},
  {nombre: "Luces Carmesí", precio: 2500, foto: "carmesi.jpg", descripcion: "Luces carmesí de 11 metros de largo con enchufe hembra en el final para agregar mas tiras de luces si necesita cubrir más espacio. Costo de envío dependiendo la zona."},
  {nombre: "Tela para ornamentar", precio: 2000, foto: "tela.jpg", descripcion: "Telas de diferentes colores para ornamentar de 10 metros x 1.50 metros. Costo de envío dependiendo la zona."},
  {nombre: "Disfraz Cabezón", precio: 3500, foto: "cabezon.jpg", descripcion: "Disfraz cabezón para adulto de Mickey, Barney, Sapo Pepe, o Pablo de Backyardigan. Costo de envío dependiendo la zona."},
  {nombre: "Toro Mecánico", precio: 26000, foto: "toroloco.jpg", descripcion: "Toro mecánico, necesita un lugar mínimo de 5x5. El alquiler es por 2hs. Hora extra: $12000"},
  {nombre: "Reloj Mecánico", precio: 26000, foto: "reloj.jpg", descripcion: "Reloj mecánico, es como una aguja de reloj que da vueltas y los niños tienen que saltarla, capacidad 4 niños a la ves, necesita un lugar mínimo de 5x5. El alquiler es por 2hs. Hora extra: $12000"},
  {nombre: "Ping Pong", precio: 5000, foto: "pingpong.jpg", descripcion: "Mesa de ping pong. El alquiler es por 3hs. Hora extra: $1000"},
  {nombre: "Inflable 3x3 de Princesas", precio: 6500, foto: "princesas.jpg", descripcion: "Inflable de princesas de 3x3. El alquiler es por 3hs. Hora extra: $2000"},
  {nombre: "Inflable 3x3 de Ben 10", precio: 6500, foto: "ben10.jpg", descripcion: "Inflable de Ben 10 de 3x3. El alquiler es por 3hs. Hora extra: $2000"},
  {nombre: "Inflable 3x4 Unisex", precio: 7500, foto: "3x4.jpg", descripcion: "Inflable unisex de 3x4. El alquiler es por 3hs. Hora extra: $2000"},
  {nombre: "Inflable 3x6 Salida de Tobogán", precio: 8500, foto: "tobogan.jpg", descripcion: "Inflable con salida de tobogán de 3x6. El alquiler es por 3hs. Hora extra: $2000"},
  {nombre: "Ring de Lucha", precio: 8500, foto: "ring.jpg", descripcion: "Ring de lucha de 5x5. El alquiler es por 3hs. Hora extra: $2000"},
  {nombre: "Plaza Blanda de 6", precio: 3500, foto: "plaza6.jpg", descripcion: "Plaza blanda de 6 nombres. El alquiler es por 3hs. Hora extra: $1000"},
  {nombre: "Plaza Blanda de 10", precio: 5000, foto: "plaza10.jpg", descripcion: "Plaza blanda de 10 nombres. El alquiler es por 3hs. Hora extra: $1500"},
  {nombre: "Plaza Blanda de 15", precio: 6000, foto: "plaza15.jpg", descripcion: "Plaza blanda de 15 nombres. El alquiler es por 3hs. Hora extra: $1500"},
  {nombre: "Metegol", precio: 4000, foto: "metegol.jpg", descripcion: "Mesa de metegol. El alquiler es por 3hs.  Hora extra: $1000"},
  {nombre: "Tejo", precio: 4000, foto: "tejo.jpg", descripcion: "Mesa de tejo, juegan de a 2. El alquiler es por 3hs. Hora extra: $1000"},
  {nombre: "Tri Tejo", precio: 4500, foto: "tritejo.jpg", descripcion: "Mesa de tejo para que  jueguen de a 3. El alquiler es por 3hs. Hora extra: $1000"},
  {nombre: "Penta Tejo", precio: 5000, foto: "pentatejo.jpg", descripcion: "Mesa de tejo, para que jueguen de a 5. El alquiler es por 3hs. Hora extra: $1000"}
]
