let arrayJuegos = [
  {juego: "Salón de Fiestas", precio: 15000, foto: "foto3.png", descripcion: "Salon de fiestas Taurum, incluye freezer grande, horno pizzero, microondas, aire acondicionado frio calor, y ventilador. Se entrega limpio a las 9 de la mañana y tiene hasta las 3.30 de la madrugada. Al finalizar nos encargamos nosotros de la limpieza. La capacidad es hasta 90 personas."},
  {juego: "Dj, Sonido e Iluminación", precio: 13000, foto: "sonido.jpg", descripcion: "Dj en vivo mas sonido e iluminación en el salón, el servicio es de 7 horas."},
  {juego: "Proyector y Pantalla", precio: 5000, foto: "pantalla.jpg", descripcion: "Proyector mas pantalla grande para la proyección de video"},
  {juego: "Animador", precio: 4500, foto: "animador.jpg", descripcion: "El animador es como el locutor de la fiesta, el que le pone onda, no es animación para niños."},
  {juego: "Parlante chico mas luces", precio: 4500, foto: "parlante.jpg", descripcion: "Parlante chico con conección bluetooth, cable o pendrive. Cuenta con micrófono, luz láser, 2 luces audiorítmicas."},
  {juego: "Ornamentación", precio: 10000, foto: "foto7.png", descripcion: "La ornamentación es para nuestro salón, incluye colgado y armado de telas, cortinado, accesorios y algunos globos, puede agregar mas si desea."},
  {juego: "Servicio de vestir", precio: 400, foto: "foto8.png", descripcion: "El servicio de vestir mesas y sillas incluye solo el trabajo de armar 1 mesa con su mantel y cubresilla mas las 10 sillas con sus vestidos y moños."},
  {juego: "Panchera Grande", precio: 1850, foto: "panchera.jpg", descripcion: "Panchera grande, no incluye el gas, puede pedir con gas sumandole el precio de la carga de gas de la garrafa."},
  {juego: "Candelabro 15 velas", precio: 1500, foto: "candelabro.jpg", descripcion: "Candelabro para poner las 15 velas de los 15 años."},
  {juego: "Freezer Grande", precio: 2500, foto: "freezer.jpg", descripcion: "Freezer grande 460 litros 1,65mts x 0,70mt."},
  {juego: "Barra de Tragos", precio: 2500, foto: "barra.jpg", descripcion: "Barra de tragos con luces mas enchufes para licuadora y demas accesorios que necesite enchufar."},
  {juego: "Sillas Princesas", precio: 40, foto: "silla.jpg", descripcion: "Silla plastica negra estilo princesa."},
  {juego: "Vestido de Sillas", precio: 40, foto: "vestido.jpg", descripcion: "Vestido de silla princesa color blanco."},
  {juego: "Lazo de Silla", precio: 10, foto: "moños.jpg", descripcion: "Lazos para los moños de las sillas, colores a elección"},
  {juego: "Mesa Ovalada", precio: 280, foto: "ovalada.jpg", descripcion: "Mesa ovalada, para 10 personas."},
  {juego: "Mesa Rectangular", precio: 280, foto: "rectangular.jpg", descripcion: "Mesa rectangular, para 10 personas, medida aproximada 2 metros."},
  {juego: "Mantel Ovalado", precio: 300, foto: "mantelred.jpg", descripcion: "Mantel ovalado color blanco."},
  {juego: "Mantel Rectangular", precio: 300, foto: "mantrect.jpg", descripcion: "Mantel rectangular color blanco."},
  {juego: "Camino de Mesa", precio: 50, foto: "camino.jpg", descripcion: "Caminos de mesa de colores varios."},
  {juego: "Alfombra Roja", precio: 1000, foto: "alfombra.jpg", descripcion: "Alfombra roja de unos 10 metros de largo para entradas."},
  {juego: "Candy Bar Carrosa", precio: 2500, foto: "candy.jpg", descripcion: "Candy bar grande en forma de carrosa, mesa con marco de selfile atras y ruedas de carruaje mas caballo. Para poner la torta y/o mesa dulce."},
  {juego: "Cuchillo", precio: 6, foto: "cuchillo.jpg", descripcion: "Cuchillo."},
  {juego: "Tenedor", precio: 6, foto: "tenedor.jpg", descripcion: "Tenedor."},
  {juego: "Cuchara", precio: 6, foto: "cuchara.jpg", descripcion: "Cuchara."},
  {juego: "Cucharita", precio: 6, foto: "cucharita.jpg", descripcion: "Cucharita postre."},
  {juego: "Panera", precio: 25, foto: "panera.jpg", descripcion: "Panera plástica."},
  {juego: "Jarra de Vidrio", precio: 50, foto: "jarra.jpg", descripcion: "Jarra de vidrio de 1 litro aproximadamente."},
  {juego: "Bandeja de Moso", precio: 65, foto: "bandeja.jpg", descripcion: "Bandeja de moso plateada grande."},
  {juego: "Salero", precio: 15, foto: "salero.jpg", descripcion: "Salero."},
  {juego: "Servilletero", precio: 20, foto: "servilletero.jpg", descripcion: "Servilletero de metal."},
  {juego: "Ensaladera", precio: 50, foto: "ensaladera.jpg", descripcion: "Ensaladera de vidrio."},
  {juego: "Compotera", precio: 30, foto: "compotera.jpg", descripcion: "Compotera de vidrio."},
  {juego: "Hielera", precio: 20, foto: "hielera.jpg", descripcion: "Hilera de metal con pinza."},
  {juego: "Platito de Postre", precio: 20, foto: "platito.jpg", descripcion: "Plato chico de postre, de porcelana."},
  {juego: "Plato playo", precio: 40, foto: "plato.jpg", descripcion: "Plato playo principal de porcelana."},
  {juego: "Copa", precio: 25, foto: "copa.jpg", descripcion: "Copa de vidrio estilo copa de vino."},
  {juego: "Copa Champagne", precio: 25, foto: "champagne.jpg", descripcion: "Copa fina para champagne."},
  {juego: "Vaso Trago Largo", precio: 25, foto: "vaso.jpg", descripcion: "Vaso fino alto estilo trago largo."},
  {juego: "Taza con Platito", precio: 50, foto: "taza.jpg", descripcion: "Taza con platito de porcelana."},
  {juego: "Azucarera", precio: 25, foto: "azucarera.jpg", descripcion: "Azucarera de vidrio y metal."},
  {juego: "Luces Carmesí", precio: 1250, foto: "carmesi.jpg", descripcion: "Luces carmesí de 11 metros de largo con enchufe hembra en el final para agregar mas tiras de luces si necesita cubrir más espacio."},
  {juego: "Tela para ornamentar", precio: 1500, foto: "tela.jpg", descripcion: "Telas de diferentes colores para ornamentar de 20 metros x 1.50 metros"},
  {juego: "Disfraz Cabezón", precio: 1500, foto: "cabezon.jpg", descripcion: "Disfraz cabezón para adulto de Mickey, Barney, Sapo Pepe, o Pablo de Backyardigan."},
  {juego: "Toro Mecánico", precio: 14000, foto: "toroloco.jpg", descripcion: "Toro mecánico, necesita un lugar mínimo de 5x5 con acceso para vehículo hasta el lugar donde va a armar el juego. El alquiler es por 2hs"},
  {juego: "Reloj Mecánico", precio: 14000, foto: "reloj.jpg", descripcion: "Reloj mecánico, es como una aguja de reloj que da vueltas y los niños tienen que saltarla, capacidad 4 niños a la ves, necesita un lugar mínimo de 5x5. El alquiler es por 2hs"},
  {juego: "Ping Pong", precio: 2500, foto: "pingpong.jpg", descripcion: "Mesa de ping pong. El alquiler es por 3hs"},
  {juego: "Inflable de Princesas", precio: 3500, foto: "princesas.jpg", descripcion: "Inflable de princesas de 3x3. El alquiler es por 3hs"},
  {juego: "Inflable de Ben 10", precio: 3500, foto: "ben10.jpg", descripcion: "Inflable de Ben 10 de 3x3. El alquiler es por 3hs"},
  {juego: "Inflable Unisex", precio: 3800, foto: "3x4.jpg", descripcion: "Inflable unisex de 3x4. El alquiler es por 3hs"},
  {juego: "Inflable Salida de Tobogán", precio: 4300, foto: "tobogan.jpg", descripcion: "Inflable con salida de tobogán de 3x6. El alquiler es por 3hs"},
  {juego: "Ring de Lucha", precio: 4500, foto: "ring.jpg", descripcion: "Ring de lucha de 5x5. El alquiler es por 3hs"},
  {juego: "Plaza Blanda de 6", precio: 1800, foto: "plaza6.jpg", descripcion: "Plaza blanda de 6 juegos. El alquiler es por 3hs"},
  {juego: "Plaza Blanda de 10", precio: 2600, foto: "plaza10.jpg", descripcion: "Plaza blanda de 10 juegos. El alquiler es por 3hs"},
  {juego: "Plaza Blanda de 15", precio: 3300, foto: "plaza15.jpg", descripcion: "Plaza blanda de 15 juegos. El alquiler es por 3hs"},
  {juego: "Metegol", precio: 1800, foto: "metegol.jpg", descripcion: "Mesa de metegol. El alquiler es por 3hs"},
  {juego: "Tejo", precio: 1800, foto: "tejo.jpg", descripcion: "Mesa de tejo, juegan de a 2. El alquiler es por 3hs"},
  {juego: "Tri Tejo", precio: 2000, foto: "tritejo.jpg", descripcion: "Mesa de tejo para que  jueguen de a 3. El alquiler es por 3hs"},
  {juego: "Penta Tejo", precio: 2500, foto: "pentatejo.jpg", descripcion: "Mesa de tejo, para que jueguen de a 5. El alquiler es por 3hs"}
]